# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "https://amcsz.me"

[_.globalMeta]
title = "amcsz"
description = "My personal website!"
longDescription = "My personal website. You can take a look at who I am, my past projects, and maybe my terrible blog posts."
cardImage = "https://amcsz.me/mountains-modified.png"
keywords = ["competitive programming", "amcsz", "ctf"]

[_.blogMeta]
title = "Blog"
description = "Technical blog posts."
cardImage = "https://amcsz.me/mountains-modified.png"
keywords = ["competitive programming", "amcsz", "ctf"]

[_.projectMeta]
title = "Projects"
description = "A list of my projects."
longDescription = "A list of the things I've done in the past that include programming."
cardImage = "https://amcsz.me/mountains-modified.png"
keywords = ["competitive programming", "amcsz", "ctf"]

[_.notFoundMeta]
title = "404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist."
cardImage = "https://amcsz.me/mountains-modified.png"

[_.hero]
title = "amcsz's blog"
subtitle = "hey there!"
image = "https://amcsz.me/mountains-modified.png"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "amcsz"
githubProfile = "https://github.com/amcsz"
linkedinProfile = "https://www.linkedin.com/in/samuel-chow-5a8b942b1/"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"